### ISSUE TITLE
Wrong HTML structure for fr email templates

### ISSUE THREAD

**Issue by Pierre-Lannoy** [panelalpha/PanelAlpha-Translations#3]
Hello!
All email templates for French language have not a valid HTML structure and are full of sentences which are not from original source. I don't understand how this could have happened because other languages, as far as I understand them, seems ok.
As I want to contribute to this French translation - and don't want to start with something definitely wrong - could you regenerate these templates for French?

Thanks a lot.

**Comment by damianwiluszeu** [comment]
Hello Pierre, 

We sincerely apologize for the inconvenience regarding the French email templates. Rest assured, we will regenerate and correct these templates to ensure they meet the expected standards. Once the templates are updated, we will notify you immediately.

We appreciate your patience and your willingness to contribute to the French translation.

Thank you for your understanding.

**Comment by damianwiluszeu** [comment]
Hello @Pierre-Lannoy, 

I have made changes to the French translations for the email templates, and it should now work correctly. Additionally, I've made a small modification to the translation synchronization script. Please re-download the update script using the following command:

- `curl -sL -o /opt/panelalpha/sync-translations.sh https://raw.githubusercontent.com/panelalpha/PanelAlpha-Translations/feature/sync-translations/scripts/sync-translations.sh`

After that, run the script with the command:

- `bash /opt/panelalpha/sync-translations.sh --lang "fr"`

**Comment by Pierre-Lannoy** [comment]
Thanks @damianwiluszeu!
There are still a few small structural errors, but as I've identified them, I'll correct them... as soon as I've done a PR for the client area translation.
